apiVersion: v1
kind: ConfigMap
metadata:
  name: jira-mcp-config
  namespace: jira-mcp
  labels:
    app: jira-mcp-server
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  HEALTH_CHECK_PORT: "8080"
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX_REQUESTS: "30"
  CACHE_TTL_MINUTES: "15"
  REQUEST_TIMEOUT_MS: "10000"
  MAX_EXECUTION_TIME_MS: "30000"