{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jira-mcp-server.fullname" . }}
  labels:
    {{- include "jira-mcp-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.jiraHost }}
  JIRA_HOST: {{ .Values.secrets.jiraHost | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jiraEmail }}
  JIRA_EMAIL: {{ .Values.secrets.jiraEmail | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jiraApiToken }}
  JIRA_API_TOKEN: {{ .Values.secrets.jiraApiToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.slackWebhookUrl }}
  SLACK_WEBHOOK_URL: {{ .Values.secrets.slackWebhookUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.teamsWebhookUrl }}
  TEAMS_WEBHOOK_URL: {{ .Values.secrets.teamsWebhookUrl | b64enc | quote }}
  {{- end }}
{{- end }}