{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jira-mcp-server.serviceAccountName" . }}
  labels:
    {{- include "jira-mcp-server.labels" . | nindent 4 }}
  annotations:
    {{- include "jira-mcp-server.serviceAccountAnnotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}