apiVersion: v1
kind: Service
metadata:
  name: {{ include "jira-mcp-server.fullname" . }}
  labels:
    {{- include "jira-mcp-server.labels" . | nindent 4 }}
  annotations:
    {{- include "jira-mcp-server.serviceAnnotations" . | nindent 4 }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "jira-mcp-server.selectorLabels" . | nindent 4 }}